name: 'Public-CI'

on: [push, pull_request]

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:

# Super-linter consists of several lint tools
# lint tools are assigned to the pipeline via the env field
# For more information, please see https://github.com/github/super-linter
  super-linter:
    permissions:
      contents: read  # for actions/checkout to fetch code
      statuses: write  # for github/super-linter to mark status of each linter run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: super-linter
      uses: github/super-linter@v7
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          VALIDATE_BASH: true
          VALIDATE_GO: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_CLANG_FORMAT: true
          VALIDATE_JSON: true

# Build stage executes binary builds for CNI and device-plugin
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25

    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install -y wget build-essential golang libbsd-dev libelf-dev libjson-c-dev\
            libnl-3-dev libnl-cli-3-dev libnuma-dev libpcap-dev meson\
            pkg-config wget zstd clang llvm gcc-multilib m4

    - name: Install libbpf
      run: |
          wget -q -O - https://github.com/libbpf/libbpf/archive/refs/tags/v1.5.0.tar.gz \
          | tar -xzC "${GITHUB_WORKSPACE}" \
          && sudo make -j -C "${GITHUB_WORKSPACE}"/libbpf-1.5.0/src install \
          && sudo rm -rf "${GITHUB_WORKSPACE}"/libbpf-1.5.0

    - name: Install libxdp
      run: |
          wget -q -O - https://github.com/xdp-project/xdp-tools/releases/download/v1.4.2/xdp-tools-1.4.2.tar.gz \
          | tar -xzC "${GITHUB_WORKSPACE}" \
          && cd "${GITHUB_WORKSPACE}"/xdp-tools-1.4.2 && ./configure && cd - \
          && sudo make -j -C "${GITHUB_WORKSPACE}"/xdp-tools-1.4.2 PREFIX=/usr install \
          && sudo rm -rf "${GITHUB_WORKSPACE}"/xdp-tools-1.4.2 \
          && pkg-config --libs --static libelf

    - name: Run build
      run: make fixup && make build

# go-static-tools scans code base and packages using go-vet, go mod verify and staticcheck
  go-static-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25

    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install -y wget build-essential golang libbsd-dev libelf-dev libjson-c-dev\
            libnl-3-dev libnl-cli-3-dev libnuma-dev libpcap-dev meson\
            pkg-config wget zstd clang llvm gcc-multilib m4

    - name: Install libbpf
      run: |
          wget -q -O - https://github.com/libbpf/libbpf/archive/refs/tags/v1.5.0.tar.gz \
          | tar -xzC "${GITHUB_WORKSPACE}" \
          && sudo make -j -C "${GITHUB_WORKSPACE}"/libbpf-1.5.0/src install \
          && sudo rm -rf "${GITHUB_WORKSPACE}"/libbpf-1.5.0

    - name: Install libxdp
      run: |
          wget -q -O - https://github.com/xdp-project/xdp-tools/releases/download/v1.4.2/xdp-tools-1.4.2.tar.gz \
          | tar -xzC "${GITHUB_WORKSPACE}" \
          && cd "${GITHUB_WORKSPACE}"/xdp-tools-1.4.2 && ./configure && cd - \
          && sudo make -j -C "${GITHUB_WORKSPACE}"/xdp-tools-1.4.2 PREFIX=/usr install \
          && sudo rm -rf "${GITHUB_WORKSPACE}"/xdp-tools-1.4.2 \
          && pkg-config --libs --static libelf

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: run static analysis
      run: make static-ci

# unit-test stage
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25

    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install -y wget build-essential golang libbsd-dev libelf-dev libjson-c-dev\
            libnl-3-dev libnl-cli-3-dev libnuma-dev libpcap-dev meson\
            pkg-config wget zstd clang llvm gcc-multilib m4

    - name: Install libbpf
      run: |
          wget -q -O - https://github.com/libbpf/libbpf/archive/refs/tags/v1.5.0.tar.gz \
          | tar -xzC "${GITHUB_WORKSPACE}" \
          && sudo make -j -C "${GITHUB_WORKSPACE}"/libbpf-1.5.0/src install \
          && sudo rm -rf "${GITHUB_WORKSPACE}"/libbpf-1.5.0

    - name: Install libxdp
      run: |
          wget -q -O - https://github.com/xdp-project/xdp-tools/releases/download/v1.4.2/xdp-tools-1.4.2.tar.gz \
          | tar -xzC "${GITHUB_WORKSPACE}" \
          && cd "${GITHUB_WORKSPACE}"/xdp-tools-1.4.2 && ./configure && cd - \
          && sudo make -j -C "${GITHUB_WORKSPACE}"/xdp-tools-1.4.2 PREFIX=/usr install \
          && sudo rm -rf "${GITHUB_WORKSPACE}"/xdp-tools-1.4.2 \
          && pkg-config --libs --static libelf

    - name: unit-tests
      run: make test
